# Change these values based on your preferences
# Note that as hashtags (#) are used for comments, any color fields will not accept hexadecimals with # at the start
# Please enter hex codes as just the code
# This config file is only read once, at program start. To change values, please restart the application
# You can also edit all these fields (and much more) manually in index.html


[Required]

spotify_Client_ID = 
# Your Spotify Client ID, from Spotify Developer Dashboard

spotify_Client_Secret = 
# Your Spotify Client Secret, from Spotify Developer Dashboard

http_Redirect = 
# Your Spotify Redirect URI, from Spotify Developer Dashboard


[Function]

http_Port = 6868
# The port that the websocket uses to connect to a localhost (127.0.0.1:port)
# Highly personal, some applications lock down certain ports
# Default: 6868
# Accepted values: any 4-digit integer 

enable_Text_Scrolling = True
# Whether to enable text scrolling in the player
# Only occurs if the text is wider than the player itself
# Default: True
# Accepted values: booleans (True/False)


[Visuals]

player_Width = 420
# The width of the player itself, in pixels
# Values too small may cut long titles/artists/albums
# Note that there's a padding of 12px per side
# Default: 420
# Accepted values: any integer 

player_Height = 90
# The height of the player itself, in pixels
# Values too small may cause image to morph strangely
# Note that there's a padding of 12px per side
# Default: 90
# Accepted values: any integer

player_Opacity = 0.75
# The player area's opacity
# Default: 0.75
# Accepted values: any float between 0 and 1 (inclusive)

artist_Prefix = by
# A string to enter before the artist name(s)
# Default: by
# Accepted values: any string

album_Prefix =
# A string to enter before the album name
# Default:
# Accepted values: any string


[Title]

title_Style = Italic
# The styling of the title text (song name)
# Default: Italic
# Accepted values: Normal, Italic, Oblique

title_Weight = Bold
# The weight of the title text
# Default: Bold
# Accepted values: Normal, Bold, Lighter, Bolder, any integer (400 = Normal)

title_Color = ffffff
# The color of the title text
# Default: ffffff (white)
# Accepted values: any hexadecimal color code


[Support]

support_Styles = Italic
# The styling of the artist, album and timer texts
# Default: Italic
# Accepted values: Normal, Italic, Oblique

support_Weights = Normal
# The weight of the artist, album and timer texts
# Default: Normal
# Accepted values: Normal, Bold, Lighter, Bolder, any integer (400 = Normal)

support_Colors = ffffff
# The color of the artist, album and timer texts
# Default: ffffff (white)
# Accepted values: any hexadecimal color code


[Border]

border_Style = Solid
# The style of the border around the player
# Default: Solid
# Accepted values: None, Hidden, Dotted, Dashed, Solid, Double, Groove, Ridge, Inset, Outset

border_Color = ffffff
# The color of the borders around the player
# Default: ffffff (white)
# Accepted values: any hexadecimal color code


[Bar]

progress_Bar_Color = 1ED760
# The color of the progress bar filling up
# Default: 1ED760 (Spotify green)
# Accepted values: any hexadecimal color code

progress_Bar_Paused = FF2C00
# The color of the progress bar when paused
# Default: FF2C00 (red)
# Accepted values: any hexadecimal color code


[Twitch-Bot]

### ADVANCED ###
# Please read the documentation at https://elleffnotelf.com/guides/sbo-bot
# Find all the commands at https://elleffnotelf.com/guides/sbo-commands

enable_Twitch_Bot = True
# Whether to enable the locally hosted Twitch Bot
# This option turns on the localhost connection between programs to pass commands
# Default: False
# Accepted values: booleans (True/False)

sbo_Runs_Bot = True
# Whether SBO (the main program) should run the bot on startup
# If running manually, it's found at SBO/Bot/SPO-Bot.exe
# If True, automatically enables the Twitch Bot (overrides enable_Twitch_Bot)
# Default: False
# Accepted values: booleans (True/False)

command_Prefix = !
# What to use as the command prefix
# This is the string that precedes any commands from this program
# Not tested with longer strings or non-unicode characters, use odd strings at your own risk
# Default: !
# Accepted values: any string

enable_Playback_Control = True
# Whether to allow Twitch chat to control Spotify playback
# Included commands are: !skip, !pause, !previous, !queue
# Default: False
# Accepted values: booleans (True/False)

allow_Subscriber_Control = True
# Whether to allow Twitch subscribers to control Spotify playback
# If disabled, only VIPs, mods and streamer can use playback controls
# Default: False
# Accepted values: booleans (True/False)

twitch_Username = 
# The username for the chat to enter
# Must be your own, otherwise authentication will fail
# Accepted values: string
# http://localhost:4343/oauth?scopes=channel:bot&force_verify=true

twitch_ID = 
# The ID of the Twitch account above
# Can use a 3rd party tool to grab this
# Accepted values: int

bot_Name = 
# The username of the bot account
# Must be your own, otherwise authentication will fail
# Accepted values: string
# http://localhost:4343/oauth?scopes=user:read:chat%20user:write:chat%20user:bot&force_verify=true

bot_ID = 
# The ID of the bot account above
# Can use a 3rd party tool to grab this
# Accepted values: int

dev_Client_ID = 
# The client ID the bot needs to connect, found in the dev console
# Accepted values: string

dev_Client_Secret = 
# The client secret the bot needs to connect, found in the dev console
# Accepted values: string