# Change these values based on your preferences
# Note that as hashtags (#) are used for comments, any color fields will not accept hexadecimals with # at the start
# Please enter hex codes as just the code
# This config file is only read once, at program start. To change values, please restart the application
# You can also edit all these fields (and much more) manually in index.html (recommended for true customisation)


[Required]

spotify_Client_ID = 
# Your Spotify Client ID, from Spotify Developer Dashboard

spotify_Client_Secret = 
# Your Spotify Client Secret, from Spotify Developer Dashboard

http_Redirect =
# Your Spotify Redirect URI, from Spotify Developer Dashboard


[Function]

address_Type = Device
# The address to set the websocket to
# Device sets the address to 127.0.0.1 (only accessible on-device)
# Local sets the address to 0.0.0.0 (accessible to devices on same network)
# The page can always be accessed at localhost:port on the device that runs SBO
# Default: Device
# Accepted values: Device, Local

http_Port = 6868
# The port that the websocket uses to push the HTML out (0.0.0.0, localhost)
# Dependent on network traffic, some applications may bind ports for themselves
# The overlay uses this port, the Bot uses the next 2 ports (needs to communicate to SBO and SBO-WS)
# Default: 6868
# Accepted values: 0-65533

hide_Player_Timeout = 15
# How long the player needs to be paused for before it fades away (seconds)
# If set to 0, disables the hide behavior
# Default: 15
# Accepted values: any integer


[Visuals]

artist_Prefix = by
# A string to enter before the artist name(s)
# Default: by
# Accepted values: any string

album_Prefix =
# A string to enter before the album name
# Default:
# Accepted values: any string


[Title]

title_Style = Italic
# The styling of the title text (song name)
# Default: Italic
# Accepted values: Normal, Italic, Oblique

title_Weight = Bold
# The weight of the title text
# Default: Bold
# Accepted values: Normal, Bold, Lighter, Bolder, any integer (400 = Normal)

title_Color = ffffff
# The color of the title text
# Multiple colors can be defined for a gradient effect
# Default: ffffff (white)
# Accepted values: any hexadecimal color code, comma-separated codes


[Support]

support_Styles = Italic
# The styling of the artist and album texts
# Default: Italic
# Accepted values: Normal, Italic, Oblique

support_Weights = Bold
# The weight of the artist and album texts
# Default: Bold
# Accepted values: Normal, Bold, Lighter, Bolder, any integer (400 = Normal)

support_Colors = ffffff
# The color of the artist and album texts
# Multiple colors can be defined for a gradient effect
# Default: ffffff (white)
# Accepted values: any hexadecimal color code, comma-separated codes


[Border]

border_Color = ff0000, 00ff00, 0000ff
# The color(s) of the border around the player
# Multiple colors can be defined for a gradient effect
# Default: ff0000, 00ff00, 0000ff (red, green, blue)
# Accepted values: any hexadecimal color code, comma-separated codes


[Bar]

progress_Bar_Color = 1ED760
# The color of the progress bar filling up
# Multiple colors can be defined for a gradient effect
# Default: 1ED760 (Spotify green)
# Default: ff0000, 00ff00, 0000ff (red, green, blue)
# Accepted values: any hexadecimal color code, comma-separated codes

progress_Bar_Paused = FF2C00
# The color of the progress bar when paused
# Default: FF2C00 (red)
# Accepted values: any hexadecimal color code


[Twitch-Bot]

### ADVANCED ###
# Please read the documentation at https://elleffnotelf.com/guides/sbo-bot
# For individual command control, use the commandConfig.ini file in SBO/Bot/

enable_Twitch_Bot = False
# Whether to enable the locally hosted Twitch Bot
# This option turns on the localhost connection between programs to pass commands
# The port for this connection is the http_Port + 1
# If running the bot manually, please ensure this is enabled - commands will not function if this is disabled
# Default: False
# Accepted values: boolean (True/False)

sbo_Runs_Bot = False
# Whether SBO (the main program) should run SBO-Bot.exe on startup
# If running manually, it's found at SBO/Bot/SBO-Bot.exe
# If True, automatically enables the Twitch Bot connection (overrides enable_Twitch_Bot)
# Default: False
# Accepted values: boolean (True/False)

command_Prefix = !
# What to use as the command prefix
# This is the string that precedes any commands from this program
# Not tested with longer strings or non-unicode characters, use odd strings at your own risk
# Default: !
# Accepted values: any string

enable_Cooldown_Messages = False
# Whether to reply to command requests that are on cooldown
# If a command is on cooldown (chatter or channel), replies with a warning
# Default: False
# Accepted values: boolean (True/False)

twitch_Username = 
# The username for the chat to enter
# Must be your own, otherwise authentication will fail
# Accepted values: string
# http://localhost:4343/oauth?scopes=channel:bot&force_verify=true

twitch_ID = 
# The ID of the Twitch account above
# Can use a 3rd party tool to grab this
# Accepted values: int

bot_Username = 
# The username of the bot account
# Must be your own, otherwise authentication will fail
# Accepted values: string
# http://localhost:4343/oauth?scopes=user:read:chat%20user:write:chat%20user:bot&force_verify=true

bot_ID = 
# The ID of the bot account above
# Can use a 3rd party tool to grab this
# Accepted values: int

dev_Client_ID = 
# The client ID the bot needs to connect, found in the Twitch dev console
# Accepted values: string

dev_Client_Secret = 
# The client secret the bot needs to connect, found in the Twitch dev console
# Accepted values: string