# This config controls the SBO Bot's command functionality
# Each command can be toggled on and off, and their cooldowns and required user levels set
# The hierarchy of "required level" is: all < subscriber < VIP/Artist < mod < lead mod < streamer
# Missing values in any field will use the default values instead
# To find out more about each command, go to https://elleffnotelf.com/guides/sbo-commands

### Requests ###



[Playlist]

enable = True
# Whether to enable the playlist command
# Default: True
# Accepted values: booleans (True/False)

cooldown_Chatter = 600
# The cooldown applied per chatter (seconds)
# Default: 600
# Accepted values: int

cooldown_Channel = 60
# The cooldown applied per channel (seconds)
# Default: 60
# Accepted values: int

required_Level = all
# The required level to use the command
# Default: all
# Accepted values: all, subscriber, VIP, mod, lead mod, streamer



[Album]

enable = True
# Whether to enable the album command
# Default: True
# Accepted values: booleans (True/False)

cooldown_Chatter = 300
# The cooldown applied per chatter (seconds)
# Default: 300
# Accepted values: int

cooldown_Channel = 30
# The cooldown applied per channel (seconds)
# Default: 30
# Accepted values: int

required_Level = all
# The required level to use the command
# Default: all
# Accepted values: all, subscriber, VIP, mod, lead mod, streamer



[Song]

enable = True
# Whether to enable the song command
# Aliases: track
# Default: True
# Accepted values: booleans (True/False)

cooldown_Chatter = 180
# The cooldown applied per chatter (seconds)
# Default: 180
# Accepted values: int

cooldown_Channel = 30
# The cooldown applied per channel (seconds)
# Default: 30
# Accepted values: int

required_Level = all
# The required level to use the command
# Default: all
# Accepted values: all, subscriber, VIP, mod, lead mod, streamer



### Playback Control ###



[Pause]

enable = True
# Whether to enable the pause command
# Default: True
# Accepted values: booleans (True/False)

cooldown_Chatter = 180
# The cooldown applied per chatter (seconds)
# Default: 180
# Accepted values: int

cooldown_Channel = 60
# The cooldown applied per channel (seconds)
# Default: 60
# Accepted values: int

required_Level = VIP
# The required level to use the command
# Default: VIP
# Accepted values: all, subscriber, VIP, mod, lead mod, streamer



[Resume]

enable = True
# Whether to enable the resume command
# Aliases: continue, play
# Default: True
# Accepted values: booleans (True/False)

cooldown_Chatter = 180
# The cooldown applied per chatter (seconds)
# Default: 180
# Accepted values: int

cooldown_Channel = 60
# The cooldown applied per channel (seconds)
# Default: 60
# Accepted values: int

required_Level = VIP
# The required level to use the command
# Default: VIP
# Accepted values: all, subscriber, VIP, mod, lead mod, streamer



[Skip]

enable = True
# Whether to enable the skip command
# Default: True
# Accepted values: booleans (True/False)

cooldown_Chatter = 180
# The cooldown applied per chatter (seconds)
# Default: 180
# Accepted values: int

cooldown_Channel = 60
# The cooldown applied per channel (seconds)
# Default: 60
# Accepted values: int

required_Level = VIP
# The required level to use the command
# Default: VIP
# Accepted values: all, subscriber, VIP, mod, lead mod, streamer



[Previous]

enable = True
# Whether to enable the previous command
# Default: True
# Accepted values: booleans (True/False)

cooldown_Chatter = 180
# The cooldown applied per chatter (seconds)
# Default: 180
# Accepted values: int

cooldown_Channel = 60
# The cooldown applied per channel (seconds)
# Default: 60
# Accepted values: int

required_Level = VIP
# The required level to use the command
# Default: VIP
# Accepted values: all, subscriber, VIP, mod, lead mod, streamer



[Queue]

enable = True
# Whether to enable the queue command
# Default: True
# Accepted values: booleans (True/False)

cooldown_Chatter = 180
# The cooldown applied per chatter (seconds)
# Default: 180
# Accepted values: int

cooldown_Channel = 60
# The cooldown applied per channel (seconds)
# Default: 60
# Accepted values: int

required_Level = VIP
# The required level to use the command
# Default: VIP
# Accepted values: all, subscriber, VIP, mod, lead mod, streamer



[Text Color]

enable = True
# Whether to enable the textColor command
# Aliases: textC
# Default: True
# Accepted values: booleans (True/False)

cooldown_Chatter = 180
# The cooldown applied per chatter (seconds)
# Default: 180
# Accepted values: int

cooldown_Channel = 60
# The cooldown applied per channel (seconds)
# Default: 60
# Accepted values: int

required_Level = subscriber
# The required level to use the command
# Default: subscriber
# Accepted values: all, subscriber, VIP, mod, lead mod, streamer



[Song Color]

enable = True
# Whether to enable the songColor command
# Aliases: songC
# Default: True
# Accepted values: booleans (True/False)

cooldown_Chatter = 180
# The cooldown applied per chatter (seconds)
# Default: 180
# Accepted values: int

cooldown_Channel = 60
# The cooldown applied per channel (seconds)
# Default: 60
# Accepted values: int

required_Level = subscriber
# The required level to use the command
# Default: subscriber
# Accepted values: all, subscriber, VIP, mod, lead mod, streamer



[Bar Color]

enable = True
# Whether to enable the barColor command
# Aliases: barC
# Default: True
# Accepted values: booleans (True/False)

cooldown_Chatter = 180
# The cooldown applied per chatter (seconds)
# Default: 180
# Accepted values: int

cooldown_Channel = 60
# The cooldown applied per channel (seconds)
# Default: 60
# Accepted values: int

required_Level = subscriber
# The required level to use the command
# Default: subscriber
# Accepted values: all, subscriber, VIP, mod, lead mod, streamer



[Overlay Color]

enable = True
# Whether to enable the overlayColor command
# Aliases: overlayC
# Default: True
# Accepted values: booleans (True/False)

cooldown_Chatter = 180
# The cooldown applied per chatter (seconds)
# Default: 180
# Accepted values: int

cooldown_Channel = 60
# The cooldown applied per channel (seconds)
# Default: 60
# Accepted values: int

required_Level = subscriber
# The required level to use the command
# Default: subscriber
# Accepted values: all, subscriber, VIP, mod, lead mod, streamer